### PR TITLE
yaml: add hidden field for cmd option

### PR DESCRIPTION
**Pull request by crazy-max**
Like markdown, hidden flags should not be generated for yaml.

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wondering if instead we should have a "hidden" property in the YAML, so that we can decide what to do with it when generating docs from it 🤔

**Comment by crazy-max** [comment]
> 
> 
> Wondering if instead we should have a "hidden" property in the YAML, so that we can decide what to do with it when generating docs from it 🤔

Good point that could do the trick, after all yaml docs is machine processed.

**Comment by thaJeztah** [comment]
Yes, I don't know if we currently have any hidden flag that we want to show in the docs, but it's possible there's specific cases where deprecated and/or hidden flag could be useful, and that would allow us to still use them (for whatever reason)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

and, now we should check if there's hidden flags that we shouldn't show (and update the template in the https://github.com/docker/docker.github.io repository 😅)

**Comment by crazy-max** [comment]
@thaJeztah Yes my case for this PR was about buildx because [some flags](https://docs.docker.com/engine/reference/commandline/buildx_build/) should not be shown in the docs like `--cpu-*` so would be nice to handle that new filed to hide them in the docs :)

**Pull request merged**
